### ISSUE TITLE
Suggestion: Add info about the Parameters<T>  type

### ISSUE THREAD

**Issue by matthieu-foucault** [piotrwitek/react-redux-typescript-guide#107]
Suppose we have the following action creator:

```
export const add = (amount: number) => action(ADD, amount);
```

Now, the props of our connected component (assuming we are using `bindActionCreators`) would have the following interface:

```
interface Props {
  add: (amount: number) => any
}
```

There are a few issues with this approach: 
- you have a "hidden reference" to the action creator: The fact that the parameters of the `add` function in the props have to be the same as the action creator is not explicit.
- If a breaking change is made to parameters of the action creator, then the typescript error that will be displayed in the `connect` function can be hard to read (and gets harder as your component has more props). 
- The above error would be pointing to the `connect` function, instead of the component that now uses an obsolete list of parameters

Here's where the `Parameters<T>` type can help  (only in typescript 3?):
```
interface Props {
  add: (...args: Parameters<typeof actions.add>) => any
}
```

It's a bit more verbose especially for simple action creators, and it means that the component which uses these props is designed to be using an action creator, but:
 - Things are explicit (which is way better for beginners)
 - If you change the signature of the `add` action creator (e.g. removing the `amount` parameter), then the error will be displayed where the `add` prop is used.

Using the `Parameters` type and explicitely referencing the action creator may not always make sense in terms of design, but I think it is worth mentioning in the guide.

Let me know what you think (and if my example makes sense)

**Comment by piotrwitek** [comment]
Hey @matthieu-foucault, could you please elaborate what is the advantage of your proposal compared to this similar proposal? #45

**Comment by matthieu-foucault** [comment]
I did not know that the return type of `dispatch(actions.add(1))` would be the action itself. In that case, I'd say that #45 is better.
