### ISSUE TITLE
How to use with createReducer?

### ISSUE THREAD

**Issue by Dhuliang** [piotrwitek/react-redux-typescript-guide#121]
Sometimes don't want to use `switch case` grammar , use official provide function `createReducer`, the link is https://redux.js.org/recipes/reducing-boilerplate#generating-reducers

I added typescript like this:
```javascript
export interface PartialReducer<T, A> {
  (state: T, action: A): T;
}

export function createReducer<T, A extends { type: string }>(
  initialState: T,
  handlers: { [type: string]: PartialReducer<T, A> }
) {
  return function(state: T = initialState, action: A): T {
    const handler = handlers[action && action.type];
    if (!handler) {
      return state;
    }
    return handler(state, action);
  };
}
```

and `Todos` reducers is
```javascript 
createReducer<Todo[], TodosAction>([], {
  [getType(todos.add)](state = [], action): Todo[] {
    return [...state, action.payload]; //get error , don't know which payload should be 
  },
});
```

If I add the following script , it will remove error but it's hard to use.
```javascript
export type TodosAddAction = ActionType<typeof todos.add>;
[getType(todos.add)](state = [], action: TodosAddAction): Todo[] {
    return [...state, action.payload]; 
  },
}
```
Can help improve above function? Thanks !
#

**Comment by piotrwitek** [comment]
I solved this, I'll add it soon as a new section in the guide as I think it is usefull.

**Comment by piotrwitek** [comment]
For reference this issue is continued here: #106

**Comment by piotrwitek** [comment]
For reference this issue is continued here: https://github.com/piotrwitek/typesafe-actions/issues/106
