### ISSUE TITLE
How to re-export interface in an ambient module ?

### ISSUE THREAD

**Issue by chawax** [piotrwitek/react-redux-typescript-guide#137]
Hi,

In my app I have code for API Client generated from Swagger Code Gen. The code includes models such as this : 

```
export interface Echelon {
    id?: number;
    code?: string;
    libelle?: string;
}
```

When I need to import this type, I have to use a relative import :

```
import { Echelon } from '../../../services/Api/swagger';
```

It works but I am not a fan of that. I'd like to have a import from an ambient module, something like that (i.e. the same way it works with ApplicationState in playground project) :

```
import { Echelon } from 'Models';
```

But I can't find the way do to this.

```
import { Echelon } from '../services/Api/swagger/api';
declare module 'Models' {
   export interface Echelon
}
```

Any idea ?

**Comment by piotrwitek** [comment]
Should work, make sure this file is d.ts and is located in the folder included in tsconfig

**Comment by chawax** [comment]
It is in a `.d.ts` file in the same folder than my `index.d.ts` file that is used to declare module `Types`.

Actually it looks like the problem is with exporting interfaces in an ambient module.

I tried this :

```
declare module 'Models' {
  export { Echelon } from '../services/Api/swagger/api';
}
```
But I have this error : "Import or export declaration in an ambient module declaration cannot reference module through relative module name. ts(2439)"

I also tried this but can't find the right way to write it :

```
import { Echelon } from '../services/Api/swagger/api';

declare module 'Models' {
  // ???
}
```

**Comment by piotrwitek** [comment]
If you're re-exporting existing interface, I would suggest to create a new alias for type or in case of interface create a new that extend exsiting one. Should solve the export issue.
e.g.
```ts
declare module 'Models' {
  // imports go inside for augmentation
  import { Echelon as BaseEchelon } from '../services/Api/swagger/api';

  export interface Echelon extends BaseEchelon { }
}
```

I won't go into the details because it's basics that you can learn from typescript documentation modules section.


> Note to myself:
> Extend module imports section with mention for augmentation to include imports inside

**Comment by chawax** [comment]
Thanks a lot again @piotrwitek !

**Comment by thetutlage** [comment]
I know, it's a closed issue and instead of creating a new one, lemme talk about the similar problem I am facing here.

I am trying to create an ambient module, that imports an interface from a relative path. The compiler raises an error saying relative imports are not allowed. Spent some time reading the existing issues and can't find why relative imports is an issue.

<img width="669" alt="Screen Shot 2019-05-09 at 11 30 24 AM" src="https://user-images.githubusercontent.com/1706381/57431346-21b57100-7250-11e9-9d57-eca239083c55.png">

**Comment by chpio** [comment]
Im getting the same error as @chawax with:

```ts
declare module "core-js-pure/features/iterator" {
    import { ExtendedIterator as BaseExtendedIterator } from "./utils/iter";
    interface ExtendedIterator<T> extends BaseExtendedIterator<T> { }
    export function from<T>(it: Iterable<T>): ExtendedIterator<T>;
}
```

> Import or export declaration in an ambient module declaration cannot reference module through relative module name. ts(2439)

on the import.

----

Moving the import out:

```ts
import { ExtendedIterator } from "./utils/iter";
declare module "core-js-pure/features/iterator" {
    export function from<T>(it: Iterable<T>): ExtendedIterator<T>;
}
```

results in a rather unintelligible error message:

> Invalid module name in augmentation. Module 'core-js-pure/features/iterator' resolves to an untyped module at '[...]/node_modules/core-js-pure/features/iterator/index.js', which cannot be augmented. ts(2665)

I guess you just can not define a module if there are relative imports in the same file.

----

So at least i made it compile with:

```ts
declare module "core-js-pure/features/iterator";
```

which results in *core-js-pure/features/iterator* being `any`.

**Comment by gaurav5430** [comment]
The error is due to the limitation that you can't do a relative imports inside an ambient declaration directly. You can use the import() syntax 
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#import-types
