### ISSUE TITLE
Upgrade redux-observable to v1.0.0

### ISSUE THREAD

**Issue by Dhuliang** [piotrwitek/react-redux-typescript-guide#138]

**Comment by Dhuliang** [comment]
Found that just remove `Epic` generic and fix `epicMiddleware` will get 0 error 

```javascript 
export const epicMiddleware = createEpicMiddleware({
  dependencies: services,
});
epicMiddleware.run(rootEpic);
```

But if not remove `Epic` generic  , `rootEpic` is not suitable for `epicMiddleware`

**Comment by piotrwitek** [comment]
Updated playground project with working example
