### ISSUE TITLE
React.ReactEventHandler<E> or ChangeEvent<HTMLInputElement>?

### ISSUE THREAD

**Issue by havesomeleeway** [piotrwitek/react-redux-typescript-guide#143]
README
```
React.ReactEventHandler<E>
Type representing generic event handler

const handleChange: React.ReactEventHandler<HTMLInputElement> = (ev) => { ... } 

<input onChange={handleChange} ... />
```

I'm new to TypeScript and at the moment a little confused about what type of EventHandler to use. 

In my UI, i have 3 input fields on the component and they are changed by the following function, with `ChangeEvent`

```
  handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    this.setState({[event.target.name]: event.target.value});
};
```

While it works, i.e. the fields are being changed when I perform an input, I'm not sure if I'm doing this correctly as the documentation on the README suggests to handle the event with `ReactEventHandler`.

My question is, am I using the correct event handler for my `onChange` function? If not, when should I use `ReactEventHandler` and when should I use `ChangeEvent`?

If `ChangeEvent` is indeed the one to be used, should we update the documentation?

**Comment by piotrwitek** [comment]
There are two ways that guide is describing, but is not suggesting anything:
1. Type representing generic event handler
2. Type representing more specific event handler

You can achieve the same result with both, the only difference between them is a style preference.
