### ISSUE TITLE
React Just State without Props

### ISSUE THREAD

**Issue by abnerCrack** [piotrwitek/react-redux-typescript-guide#146]
Hey piotrwitek,
i just use the state in this componet, Props is not used, Is there a better way to Handle the types of props?

```
interface IExampleState {
  name: string,
  age: number,
  width: number
}
export default class Example extends React.Component<{},IExampleState> {
  constructor(props: any) {
    super(props);
    this.state = {
      name: 'Bilbo Baggins',
      age: 25,
      width: window.innerWidth,
    };
  }
  render() {
    const { name, age, width } = this.state;
    return <div>{name}<div>
  }
}
```

**Comment by piotrwitek** [comment]
Yeah, that's fine. If you're really crazy about cleanliness I would add empty Alias Props, and use that. I'm doing that because it makes every component consistent and helps my teammates to use that later when extending the component because all the types are already in place.
