### ISSUE TITLE
Add sample with @decorator usage

### ISSUE THREAD

**Issue by peterblazejewicz** [piotrwitek/react-redux-typescript-guide#16]
The `tsconfig.json` sample suggests usage of experimental decorator flag. So it would be nice to show `@autobind` decorator removing constructor bindings. 

From this:
```tsx
  counter: number = 10;

  constructor(props: {}) {
    super(props);
    this.handleIncrement = this.handleIncrement.bind(this);
  }
  handleIncrement() {
    alert(`Increment ${this.counter}`);
  }
  render() {
    return (
      <SFCCounter
        count={4}
        label="Click Me"
        onIncrement={this.handleIncrement}
      />
    );
  }
```
to this:
```tsx
import autobind from 'autobind-decorator';
...
  counter: number = 10;
  @autobind
  handleIncrement() {
    alert(`Increment ${this.counter}`);
  }
  render() {
    return (
      <SFCCounter
        count={4}
        label="Click Me"
        onIncrement={this.handleIncrement}
      />
    );
  }
```

**Comment by piotrwitek** [comment]
Hi,
Thanks for suggestion, I'll think about adding some decorator example, but certainly not the one using 'autobind-decorator', as this would mean I support this pattern and in fact I'm not.
I prefer instance properties which are the standard way to do the same thing.

**Comment by piotrwitek** [comment]
Closing as there is nothing specific to @decorator usage in TypeScript. Use it in the same way as in pure JS.
