### ISSUE TITLE
Generic type for props for ReactElement is misleading

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [piotrwitek/react-redux-typescript-guide#161]
I'm referring to [this](https://github.com/piotrwitek/react-redux-typescript-guide#reactreactelementp-or-jsxelement) and mean that the `<P>` should be removed. That's it. :)

Reason being - it can't be used to ensure only elements with props of type `P` are assigned:
```ts
type Props = {
  bar: number
};
const MyComponent: React.FC<Props> = ({bar}) => (<div>{bar}</div>);
const element: React.ReactElement<Props> = <div />; // Works!
```

**Comment by piotrwitek** [comment]
@s-h-a-d-o-w I agree, let's fix it, accepting PR's.

**Comment by s-h-a-d-o-w** [comment]
Encountered some workflow hickups (didn't realize the contributors thing is automated and the pre-push hook failed because I first tried running it on Windows) but the error [that is thrown now](https://semaphoreci.com/piotrekwitek/react-redux-typescript-guide/branches/pull-request-162/builds/2) does not seem related to my change.

**Comment by piotrwitek** [comment]
@s-h-a-d-o-w yes I updated TS and forgot to update some HOC issues that are bugs in the compiler, I will fix it in other PR
