### ISSUE TITLE
Can't push on windows because of is-clean script

### ISSUE THREAD

**Issue by mathiassoeholm** [piotrwitek/react-redux-typescript-guide#164]
I'm trying to submit a pull request, but I can't push to my fork because the is-clean script doesn't work.

My guess it that it's because I'm using Windows. The output I get is:

```
=$(git was unexpected at this time.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ is-clean: `if output=$(git status --porcelain) && [ -z "$output" ]; then echo 'Success!'; else (echo '>>> Please check CONTRIBUTING.md to learn how to properly amend README.md <<<' && false); fi`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ is-clean script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Any ideas how to fix this? :-)

I'm making a PR for fixing the error boundary example btw, since errors are not catched if they get thrown in an event handler.

**Comment by piotrwitek** [comment]
I need to all just to be clear, did you edit Source_readme and run generate script?

**Comment by mathiassoeholm** [comment]
Yup!

I tried on another Windows computer now, with the same result. Here's the entire output if that helps:

![image](https://user-images.githubusercontent.com/1747242/56718707-8eece080-673f-11e9-937f-4a03a7fcd611.png)

Is the bash script (or whatever it is) supposed to work on Windows? It's complaining that =$(git is a syntatic error, so that might explain it.

**Comment by piotrwitek** [comment]
@mathiassoeholm yes it's a bash script, any ideas how to make it cross-platform compatible, I'm not very familiar with windows env, I would appreciate some help here.

**Comment by mathiassoeholm** [comment]
It works if I move the script into an .sh file and run it with the sh command.
See the changes on my branch here: https://github.com/mathiassoeholm/react-redux-typescript-guide/commit/5c31ec45434d3655bf329dcdf433c169fc037e9d

I can make a PR with this if you want?

Btw it only works in Git Bash, Cygwin or similar, it still doesn't work in CMD but that's expected since there's no native sh command on Windows.

**Comment by piotrwitek** [comment]
that's cool, please open a PR :👍

**Comment by mathiassoeholm** [comment]
Done!
I can open the PR I originally intended once this is merged :-)
