### ISSUE TITLE
Redux and thunk - types update to allow parameters

### ISSUE THREAD

**Issue by Daveawb** [piotrwitek/react-redux-typescript-guide#169]
Over the past few days I have been working on a project that uses `thunk` to dispatch axios requests to our API. I wanted these typed correctly and I came up with the following types to assure type completeness without `bindActionCreators`. I wanted to do this as with most thunk actions you'll want to pass arguments to the action. If you agree that this is a valid solution would you consider a PR to the documentation on your `thunk` integration sections?

This uses the built in thunk types instead of the redux types for dispatchers.

### Thunk actions
```
type ActionReturn<A> = ThunkAction<Promise<A>, {}, {}, MyType.RootAction>;

// getEntitySuccess is a standard redux action that in my case is returning an action generated
// by `typesafe-actions.action()`.

export const getEntity = (id: number): ActionReturn<ReturnType<typeof getEntitySuccess>> => {
    return (dispatch: ThunkDispatch<{}, {}, MyTypes.RootAction>) => {
        // return any async operation that returns Promise<A>
        return axios.get(`some/api/endpoint/${id}`)
            .then(res: AxiosResponse) => dispatch(getEntitySuccess(res.data);
   };
}
```

### mapDispatchToProps
```
const mapDispatchToProps = (dispatch: ThunkDispatch<{}, {}, MyType.RootAction>) => ({
    onGetEntity: (id: number) => dispatch(getEntity(id));
});
```

The above gives a strongly typed thunk action whilst allowing actions to be called without using `bindActionCreators`. The promise chain is also available and can be modified further by passing a different parameter to `<ActionReturn>`'s generic `A`.

**Comment by piotrwitek** [comment]
Hey @Daveawb and thanks for sharing.

Why you want to do this, what is the problem with `bindActionCreators` that you want to change it?

In your approach, you have to wrap and redeclare each action creator manually in mapDispatchToProps function while `bindActionCreators` is automatic. Also, there's more unnecessary boilerplate which makes it more verbose and difficult to read.

**Comment by Daveawb** [comment]
I couldn't see a way to pass variables to the different thunk actions with bindActionCreator without first partially applying them. Maybe you know a better way?

**Comment by piotrwitek** [comment]
You have explanation here: https://github.com/piotrwitek/react-redux-typescript-guide#typing-connected-component-using-redux-thunk-action-creators

This is the same as what you did but without extra types and other boilerplate code:
```ts
export const getEntity = (id: number) => (
   dispatch: Dispatch<Types.RootAction>
): Promise<ReturnType<typeof getEntitySuccess>> => {
        return axios.get(`some/api/endpoint/${id}`)
            .then(res: AxiosResponse) => dispatch(getEntitySuccess(res.data);
   };
}

const mapDispatchToProps = (dispatch: Dispatch<Types.RootAction>) =>
  bindActionCreators({
      onGetEntity: getEntity,
    }, dispatch);
```

**Comment by Daveawb** [comment]
Told you I'd missed something, this makes sense. Closing this as you already have this covered.
