### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by kvoncode** [piotrwitek/react-redux-typescript-guide#182]
Location: https://github.com/piotrwitek/react-redux-typescript-guide#reactxxxeventhtmlxxxelement

It's said that `React.XXXEvent<HTMLXXXElement>` is `Type representing more specific event handler`

Instead maybe it should be just: `Type representing more specific event`

So for example `React.MouseEvent<HTMLDivElement>` is type of mouse event that happened on `HTMLDivElement`

**Comment by piotrwitek** [comment]
Yeah that makes sense
