### ISSUE TITLE
Suggestion: Examples for new redux hooks and react-router hooks

### ISSUE THREAD

**Issue by C-Higgins** [piotrwitek/react-redux-typescript-guide#196]
Redux and React-Router have introduced new hooks that drastically change the standard patterns:

https://react-redux.js.org/api/hooks

https://reacttraining.com/blog/react-router-v5-1/

Some of these benefit from extra typescript typings that this guide could help with, such as `useDispatch` requiring you to pass the type of the dispatch for action type safety, or `useSelector` benefiting from a type override so you don't have to type the state parameter each call.

**Comment by NickSevens** [comment]
I would be very interested in this as well. @piotrwitek please consider adding an example for this as well!

**Comment by piotrwitek** [comment]
Hey @C-Higgins, thanks for creating this issue!
I was already thinking about it and will definitely add new patterns as soon as I have some time.
