### ISSUE TITLE
Regarding 'Typing connected component with redux-thunk integration' section

### ISSUE THREAD

**Issue by NickSevens** [piotrwitek/react-redux-typescript-guide#200]
Hi @piotrwitek,
Regarding the section `Typing connected component with redux-thunk integration`:
I use the guide mentioned in the _Warning_ of the docs, and this works very well in my case.

However, I was wondering if this was a temporary measure - or is this something future-proof, and still valid when updating redux-thunk, ts version, etc...?

**Comment by piotrwitek** [comment]
Hey @NickSevens,
Thanks for the info, I guess they have merged the fix that was linked in the Warning section of the docs.
In this case, I think I could finally update the docs accordingly.
