### ISSUE TITLE
MapDispatchToProps shorthand

### ISSUE THREAD

**Issue by Vanuan** [piotrwitek/react-redux-typescript-guide#205]
Is there a solution for mapDispatchToProps shorthand syntax?

```
interface IProps {
  action: () => void;
}

const MyComponent = ({ action }: IProps): JSX.Element => (
  <div onClick={action}>my component</div>
);

const action = actionCreator<null>('SOME_ACTION'); // bound to dispatch

connect(null, { action })(MyComponent);
```

I'm getting this error:

```
Type 'ActionCreator<void>' is not assignable to type '() => void'.  TS2769
```

Is there a way to fix it without changing prop types of MyComponent?

**Comment by piotrwitek** [comment]
Hey @Vanuan 
Yes, an example is here: https://github.com/piotrwitek/react-redux-typescript-guide#--redux-connected-counter-with-redux-thunk-integration

use this:
```
const mapDispatchToProps = (dispatch: Dispatch<Types.RootAction>) =>
  bindActionCreators(
    {
      onIncrement: incrementWithDelay,
    },
    dispatch
  );
```

**Comment by Vanuan** [comment]
But that's not a shorthand syntax

**Comment by Vanuan** [comment]
Shorthand syntax is this:
```
connect(null, { onIncrement: incrementWithDelay })
```

**Comment by Vanuan** [comment]
Is there any reason you want to be able to use a return value of the dispatch call?

e.g.: `props.incrementWithDelay().then(doSomethingElse)`

**Comment by Vanuan** [comment]
I've created a fix for typescript-fsa:
https://github.com/aikoven/typescript-fsa/pull/82
