### ISSUE TITLE
Add new example for non-HOC component that uses connect

### ISSUE THREAD

**Issue by ORESoftware** [piotrwitek/react-redux-typescript-guide#206]
I am looking for a TypeScript example using:

```
import {connect} from 'react-redux'
```

the first example is this one:
https://github.com/piotrwitek/react-redux-typescript-guide#--nested-hoc---wrapping-a-component-injecting-props-and-connecting-to-redux-

really? :) the first example of showing how to use TS types with connect() is a HOC? Can we get an example of using connect() with a regular non-HOC component? thx

**Comment by ORESoftware** [comment]
bump

**Comment by piotrwitek** [comment]
Hey @ORESoftware 
The section you're referring to is HOC section, not a connected component section.
Here is connected components section: https://github.com/piotrwitek/react-redux-typescript-guide#--redux-connected-counter

Could you please next time check the documentation more thoroughly, please.
