### ISSUE TITLE
100% typed covered code

### ISSUE THREAD

**Issue by codeBelt** [piotrwitek/react-redux-typescript-guide#21]
I wanted to share my [typescript-hapi-react-hot-loader-example](https://github.com/codeBelt/typescript-hapi-react-hot-loader-example) project in hope you add it to your `Project Examples`. On my repo I take the approach of _trying_ to have 100% typed code coverage. I think it could be useful for others working with TypeScript.

**Comment by piotrwitek** [comment]
Hi @codeBelt 
I didn't have a time yet, I'll to find some time during this weekend and check your repo to see if it's related to the standards outlined in this guideline.

**Comment by piotrwitek** [comment]
I have went over your repo and your representing a completely different approach that is not an example of implementation based on goals and ideas advocated in this guide, so this is a no real Project Example of this guide.
From other perspective as I have classified it as a different approach I could mention it as alternative but there is no explanation of concepts and ideas on which implementation is based on so there is no real value added in sharing it here.
