### ISSUE TITLE
Link to missing anchor in the guide

### ISSUE THREAD

**Issue by schrer** [piotrwitek/react-redux-typescript-guide#219]
## Description
Under the topic "Goals", the link with display text "complementary libraries" points to an anchor in the readme that does not exist.

## Steps to Reproduce
1. In the README, go to the paragraph titled [Goals](https://github.com/piotrwitek/react-redux-typescript-guide/blob/master/README.md#goals)
2. Third bullet point contains a link with display text "complementary libraries", pointing to https://github.com/piotrwitek/react-redux-typescript-guide/blob/master/README.md#complementary-libraries. This anchor does not exist (anymore?), so nothing really happens on click, beside a URI change in the address bar.

## Suggested solution
Looking at the history of the file and the context I assume, that the link should point to the paragraph following the "Goal" paragraph, so https://github.com/piotrwitek/react-redux-typescript-guide/blob/master/README.md#react-redux-typescript-ecosystem
If that is correct, I could create a commit making that change and open a PR, if it helps.

**Comment by piotrwitek** [comment]
Hey @schrer, you're correct, I would gladly accept a PR :)
Thanks!

**Comment by schrer** [comment]
Alright, PR is open.
Unfortunately the build did not pass, I left a comment on the PR.
