### ISSUE TITLE
Stateful component with connect

### ISSUE THREAD

**Issue by AJamesPhillips** [piotrwitek/react-redux-typescript-guide#22]
I'm using an older version of react-redux types (4.4.41) so apologies if this is incorrect.  Also apologies if I've missed the example in this guide.  I wanted a connected Stateful container.  I appreciate that perhaps containers should be stateless as they are just there to wrap the stateful components.  If this is your opinion then feel free to close this issue.  Otherwise I thought it would be useful to share the typing I use:

    import * as React from "react";
    import {connect, Dispatch} from "react-redux";

    import {AppState} from "../state/shape";
    /**
    * interface AppState {
    *     someState: number;
    * }
    */
    import {saveItemAction} from "../actions/item";
    /**
    * export const saveItemAction = () => ({type: "SAVE_ITEM"})
    */

    interface Props {
        normalProp: string;
    }

    interface PropsFromState {
        somePropFromState: number;
    }

    interface PropsFromDispatch {
        itemClicked: () => void;
    }

    interface AllProps extends Props, PropsFromState, PropsFromDispatch {}

    class MyComponent extends React.Component<AllProps, {}> {

        render() {

            return (
            <div>
                <div>normalProp: {this.props.normalProp}</div>
                <div>somePropFromState: {this.props.somePropFromState}</div>
            </div>);
        }
    }

    const map_state_to_props = (state: AppState): PropsFromState => {
        return {
          somePropFromState: state.someState,
        };
    };

    const map_dispatch_to_props = (state: AppState, dispatch: Dispatch<AppState>): PropsFromDispatch => {
        return {
            itemClicked: () => dispatch(saveItemAction()),
        };
    };

    export const ConnectedMyComponent = connect(
        map_state_to_props,
        map_dispatch_to_props
    )<Props>(MyComponent);

**Comment by piotrwitek** [comment]
Hello,
Sorry but I feel this doesn't add anything new, basically you could move a code from a component into stateless container and that's it, and it's already in the guide.
Moreover the pattern you propose is too verbose (too much explicit typing), and it is not aligned with the guide goals and motto.

Anyways, thanks for sharing your approach.
I'm closing the issue.
