### ISSUE TITLE
root action

### ISSUE THREAD

**Issue by lsentkiewicz** [piotrwitek/react-redux-typescript-guide#33]
I am confused how to create the root action properly.

From docs:

```js
// example reducer
export const reducer: Reducer<State> = (state = 0, action: RootAction) => {
```

```js
// root actions
export type RootAction =
  | ReactRouterAction
  | CountersActions[keyof CountersActions]
  | TodosActions[keyof TodosActions]
  | ToastsActions[keyof ToastsActions];
```

```js
// example action creators
import { createAction, getType } from 'react-redux-typescript';

// Action Creators
export const actionCreators = {
  incrementCounter: createAction('INCREMENT_COUNTER'),
  showNotification: createAction('SHOW_NOTIFICATION', 
    (message: string, severity: Severity = 'default') => ({
      type: 'SHOW_NOTIFICATION', payload: { message, severity },
    })
  ),
};
```

`CountersActions[keyof CountersActions]` is equal to action creator types, not action types.
Should I define both action creator and actions separately?
Also `ToastsActions[keyof ToastsActions];` doesn't work, but `typeof  ToastsActions[keyof typeof ToastsActions];` works.

**Comment by jakubrohleder** [comment]
I've just found this issue, I think it should help you: https://github.com/piotrwitek/ts-redux-actions/issues/4

**Comment by piotrwitek** [comment]
Hello @lsentkiewicz 
I'm in the middle of rework of entire action creators section because it have some time and I made a few little improvements in typings, so there will be some changes soon.

But at this moment you can check the issue linked above or check the RootAction file that is located in the Playground Project: https://github.com/piotrwitek/react-redux-typescript-guide/blob/master/playground/src/redux/root-action.ts

**Comment by piotrwitek** [comment]
Please check a new and updated [Store Configuration Section](https://github.com/piotrwitek/react-redux-typescript-guide#store-configuration)

**Comment by lsentkiewicz** [comment]
thanks @piotrwitek!

**Comment by lsentkiewicz** [comment]
In the current readme.md

```js
export const allActions = {
  ...countersAC,
  ...todosAC,
  ...toastsAC,
};

const returnOfActions =
  Object.values(allActions).map(getReturnOfExpression);
```

should be changed to
```js
export const allActions = [
  ...Object.values(countersAC),
  ...Object.values(todosAC),
  ...Object.values(toastsAC),
];

const returnOfActions = allActions.map(getReturnOfExpression);
```

because multiple modules can contain the same names.
Example `countersAC.loaded()` and `todosAC.loaded()`, and duplicated names are overriden.

**Comment by piotrwitek** [comment]
@lsentkiewicz yes that make sense, thanks!
I'll update it with the next PR which I'm working on right now.
