### ISSUE TITLE
connect stateful component

### ISSUE THREAD

**Issue by lsentkiewicz** [piotrwitek/react-redux-typescript-guide#39]
Is it expected that stateful components can't be connected to redux?
Example
```tsx
// component

export interface LayoutProps {
  user?: User;
  logout: () => any;
}
type State = {
  isOpen: boolean;
};

class Layout extends React.PureComponent<LayoutProps, State> {
}

// container

const mapState = (state: State) => ({
  user: state.global.user
});
connect(mapState, {logout})(Layout);

```
error:
```
 Type 'typeof Layout' provides no match for the signature '(props: { user: User; } & { logout: (() => { type: "global/LOGOUT"; }) & TypeGetter<"global/LOGOUT">; } & { children?: ReactNode; }, context?: any): ReactElement<any>'.
```
It works if there are no actions

Here is my workaround

```tsx
export default Layout as any as React.SFC<LayoutProps>;
```

Any thoughts? All libraries are the latest version.

**Comment by piotrwitek** [comment]
It seems the `user?` prop nullable definition and it's state counterpart which is not nullable is not matching, it's limitations of inference from React definitions and you can work over it by asserting the state definitions to match props definition. `state.global = { user?: User }`

**Comment by lsentkiewicz** [comment]
Thanks, `user?` was the problem, but both the state and components use the same definition.

It seems like it's better to use definitions `user: User | null` instead of `user?: User` because it doesn't need extra assertions.


Also, what's the easiest way to debug such problems? If there are many connected properties, it doesn't display what properties are incorrect but shows that the whole type is wrong.

**Comment by piotrwitek** [comment]
For me it's just training and experience to have a better understanding of Type Error messages, you can try to decompose complex types to simpler one, but using third party definition it's not the case.
