### ISSUE TITLE
Misleading "with default props" section

### ISSUE THREAD

**Issue by r00ger** [piotrwitek/react-redux-typescript-guide#43]
The example shown there will not work the way we except it in JSX due to the fact that compiler uses the [type of `props` in order to define types of attributes](http://www.typescriptlang.org/docs/handbook/jsx.html#attribute-type-checking).

So, basically with the code given, the next code will fail:

```ts
<StatefulCounterWithDefault label="" />;
//                          ~~~~~~~~ Property 'initialCount' is missing in type '{ label: ""; }'.
```

[There is an issue where `defaultProps` are being discussed](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/11640#issuecomment-355270345)

I'm not sure If that's a good idea to put the workaround I use there because it might be a bit too complicated for beginners:

```ts
export const User = class extends React.Component<PropsWithDefault, {}> {
    // ...
} as React.ComponentClass<Props>;
```

What do you think guys?

**Comment by piotrwitek** [comment]
Hi @r00ger,
Your'e right thanks for pointing that out 👍 
Unfortunately the proposed workaround with assertion IMO is not enough for a clean codebase.
Let's look for something better...

**Comment by piotrwitek** [comment]
I think maybe better could be to flip assertion with annotation of const like this (works the same):
```tsx
export const User: React.ComponentClass<Props> =
  class extends React.Component<PropsWithDefault, {}> {
    // ...
  };
```

**Comment by nathanvogel** [comment]
The file in which you put this workaround doesn't exist anymore, do you still recommend going this way?
