### ISSUE TITLE
suggestion: Add unit tests examples for reducers

### ISSUE THREAD

**Issue by duffbuster** [piotrwitek/react-redux-typescript-guide#49]
I'm trying to test my reducers written based off of this guide, but am having difficulty. Is there an easy way to access reducers in unit tests?

**Comment by piotrwitek** [comment]
Here you go: https://github.com/piotrwitek/react-redux-typescript-guide/blob/master/playground/src/redux/todos/reducer.spec.ts

Run with `npm test` command in playground folder.

Cheers
