### ISSUE TITLE
Maybe have some mistake on combineReducers?

### ISSUE THREAD

**Issue by incuisting** [piotrwitek/react-redux-typescript-guide#52]
Thank you very much for your guide, but there are some puzzles in my practice.
**This guide:** 
```javascript
import { combineReducers } from 'redux';
import { routerReducer, RouterState } from 'react-router-redux';

import { countersReducer, CountersState } from '@src/redux/counters';
import { todosReducer, TodosState } from '@src/redux/todos';

interface StoreEnhancerState { }

export interface RootState extends StoreEnhancerState {
  router: RouterState;
  counters: CountersState;
  todos: TodosState;
}

import { RootAction } from '@src/redux';
export const rootReducer = combineReducers<RootState, RootAction>({
  router: routerReducer,
  counters: countersReducer,
  todos: todosReducer,
});
```
combineReducers Generic with two arguments in the above example.
But in my practice ,i find combineReducers don't need two variables.
So i check the  declaration file of redux. 
``` javascript
export function combineReducers<S>(reducers: ReducersMapObject): Reducer<S>;
```
This means that only one parameter is required.
Please confirm this question。If it is wrong, please fix it。

My redux version：3.7.2

**Comment by piotrwitek** [comment]
Please check updated setup section.

**Comment by jstoeffler** [comment]
For those who run in the same issue: you need to upgrade to redux v4.x.x
