### ISSUE TITLE
Syntax error with $call and createAction

### ISSUE THREAD

**Issue by mwq27** [piotrwitek/react-redux-typescript-guide#54]
I am getting this TS compile error 
```
./src/store/ducks/auth.module.ts
Syntax error: Unexpected token, expected ] (95:41)
//My actions
export const actions = {
  signup: createAction(types.SIGNUP_REQUEST, (email: string, password: string) => ({
    type: types.SIGNUP_REQUEST,
    payload: { email, password },
  })),
....

  93 | 
  94 | const returnsOfActions = _.values(actions).map($call);
> 95 | type AppAction = typeof returnsOfActions[number];
```
It seems to be mad about the `[number]` part.  Any idea on what the issue is?

**Comment by piotrwitek** [comment]
Hi,
Please provide the TS version, and also check with standard `Object` API instead of `_`.

**Comment by mwq27** [comment]
TS version is Version 2.6.2, and I switched it to `Object.values`, but stilll getting that error.
```
Syntax error: Unexpected token, expected ] (95:41)

  93 | 
  94 | const returnsOfActions = Object.values(actions).map($call);
> 95 | type AppAction = typeof returnsOfActions[number];
     |                                          ^
  96 | export type RootAction = AppAction;
  97 | 
```

**Comment by mwq27** [comment]
Should I be doing this instead?
```js
const returnsOfActions = Object.values(actions).map($call);
type AppAction = typeof returnsOfActions;
export type RootAction = AppAction;
```

**Comment by mwq27** [comment]
Ok I think the issue with this had to do with the babel-loader.  For some reason i was still using `babel-loader` to transpile my ts, along with the `awesome-typescript-loader`.  I turned off babel-loader and switched to just using `ts-loader`, and this error stopped happening.

**Comment by piotrwitek** [comment]
Yes that make sense.
