### ISSUE TITLE
Reducer typing with redux-thunk

### ISSUE THREAD

**Issue by prog666** [piotrwitek/react-redux-typescript-guide#56]
I've got some actions

```tsx
export const setOrder = createAction('SET_ORDER', (order, id) => ({
    type: 'SET_ORDER',
    order,
    id,
}));

export const load = (id:string):ThunkAction<Promise<void>, any, void> => {
    return async (dispatch, getState):Promise<void> => {
        let result;
        try {
            result = await request(`/orders/${id}`);
            dispatch(setOrder(result, id));
        } catch (err) {
            console.error(err);
        }
    };
};
```

I create reducer as tutorial says:

```tsx
import { getType } from 'typesafe-actions';
import { setOrder } from '../actions/order';

export type OrderState = {
    readonly loaded:string | null,
    readonly order:{}, // @TODO correct type
}

const initialState:OrderState = {
    loaded: null,
    order: {},
};

const orders = (state = initialState, action: OrdersAction) => {
    switch (action.type) {
        case getType(setOrder): {
            return {
                ...state,
                order: action.order,
                loaded: action.id,
            };
        }
        default: {
            return state;
        }
    }
};

export default orders;

import { $call } from 'utility-types';
import * as actions from '../actions/order';
const returnsOfActions = Object.values(actions).map($call);
export type OrdersAction = typeof returnsOfActions[number];
```

The problem is that my action type looks like:

```tsx
(parameter) action: {
    type: "SET_ORDER";
    order: any;
    id: any;
} | ((dispatch: any, getState: () => any, extraArgument: void) => Promise<void>)
```

Looks like i should not map all actions, but select them manually. Is there any way to avoid this boilerplate?

**Comment by danizord** [comment]
Currently to avoid that I'm exporting all the normal action creators in a single `actions` export, and exporting the thunks separately.

**Comment by piotrwitek** [comment]
@prog666 I don't understand what you mean by a boilerplate here?
Basically the correct way is to do exactly what @danizord suggested and export thunks separately.
And if you want to filter out thunks from exported actions try to use a filter method, although I guess the type issues will still remain.

**Comment by prog666** [comment]
But then when i pass action creators to bindActionsCreators i have to merge them back. What I'm doing now is creating `OrdersAction` type in actions file, and composing it from manually created list of action creators. It works but i have to add new actions to the list every time i create them.
