### ISSUE TITLE
Example of chained API requests via actions?

### ISSUE THREAD

**Issue by pachuka** [piotrwitek/react-redux-typescript-guide#58]
Hello Piotr,

This guide is excellent and think this guide/repo is very useful for writing clean react/redux/typescript code.

One issue I am running into (more likely just failing to wrap my head around this) is how to handle ajax chain of requests.

For example I have a few different actions defined such as registerUser, updateProfile separated in two reducers. Now each of these actions have a corresponding epic that does an ajax call to post some data and on success returns a new action registerUserSuccess or on failure registerUserFailure. Same with updateProfile where the ajax request returns updateProfileSuccess/Failure. This all works great when called individually. What if I have a case where in another flow I have the data to both registerUser and updateProfile in the same flow and want them to occur sequentially?

Do you have any suggestions for the best way to handle this/reuse code in this scenario? Is it best to make a new action/reducer/epic flow that handles just this case, or is it possible to re-use the existing actions and have them execute sequentially depending on the result of the ajax call?

In addition it might be useful to have an API Call middleware example in the guide that allows us to reuse logic when defining <SOME_TASK>REQUEST/SUCCESS/FAIL

**Comment by piotrwitek** [comment]
Hi,
Epics are the way to handle async scenarios, and you can use them as a way to reuse already existing epics as well. Create a new epic, that will set triggers to react to some actions and then emit next actions as a way to orchestrate more complex flows. You don't need to create new actions for this you can basically react to some action and execute separate epic. Try to make them small and focused to follow Single Responsibility Principle.

Example scenario that will emit request action to fetch some dictionaries when user gets authenticated in the app:
```ts
const loadDictionaries: Epic<RootAction, RootState, Services> = (action$, store) =>
  action$
    .filter(isActionOf([
      appActions.initAuth,
    ]))
    .mergeMap(_ => Observable.from([
      dictionariesActions.getShippingMethodsRequest(),
      ...
    ]));
```
