### ISSUE TITLE
Suggestion: lower learning curve by including short tutorial

### ISSUE THREAD

**Issue by RavensburgOP** [piotrwitek/react-redux-typescript-guide#59]
This is a great resource and it has helped me tremendously. Unfortunately it's hard to understand all the intricacies from the guide itself and I believe it would help a lot if there was a few step-by-step guides on for instance how to set up a small 1 or 2 component app, how to integrate each type of component and so on.

**Comment by piotrwitek** [comment]
I think the best solution for this issue will be to create a new **Tutorials & Articles** section, that will hold a links pointing to articles/tutorials that are referring or present at least similar quality and goals with this guide.
The reason to not include tutorials directly is to keep the guide concise and focused close to a compendium / cheat-sheet format rather then step-by-step tutorial.
