### ISSUE TITLE
Incorrect action creator type when using bindActionCreators and redux-thunk

### ISSUE THREAD

**Issue by rluiten** [piotrwitek/react-redux-typescript-guide#6]
Specifically I have this action defined.
```typescript
getTransitionForm: (params: GetTransitionFormParams) =>
    (dispatch: Dispatch<RootState>, getState: () => RootState, extraArgument: any) => 
         Promise<any>;
```

When mapped as follows as per your guide from section "Connected Container without OwnProps using Type Inference" https://github.com/piotrwitek/react-redux-typescript-guide#connected-container-with-ownprops

```typescript
export const mapDispatchToProps = (dispatch: Dispatch<RootState>) =>
  bindActionCreators(
    {
      getTransitionForm,
    },
    dispatch
  );
const dispatchProps = returntypeof(mapDispatchToProps);
```
The resulting value of dispatchProps is
```typescript
const dispatchProps: {
    getTransitionForm: (params: GetTransitionFormParams) =>
        (dispatch: Dispatch<RootState>, getState: () => RootState, extraArgument: any) => 
             Promise<any>;
}
```

I believe after binding it should be.
```typescript
const dispatchProps: {
    getTransitionForm: (params: GetTransitionFormParams) => Promise<any>;
}
```
Which I expect is not going to be easy to derive.
I only discovered this as I wanted to do something with the returned promise.
Thanks for your great guide.

**Comment by piotrwitek** [comment]
@rluiten hello
this is bindActionCreators declaration:
```
export function bindActionCreators<M extends ActionCreatorsMapObject>(actionCreators: M, dispatch: Dispatch<any>): M;
```

As you can see it will return ActionCreatorsMapObject, so resulting value of dispatchProps is perfectly fine because it is then used by connect to hook up to the component.
Moreover when you check the type of `getTransitionForm` prop in the connected component you will find you have exactly the type you have expected after the binding.

This is what I have in my project, the dispatched action is returning a Promise with updated model or undefined:
```
const updatedRegion = await this.props.updateRegion(region); // updateRegion: (payload: RegionModel) => (dispatch: Dispatch<RootState>, getState: () => RootState) => Promise<void | RegionModel | undefined>
```

**Comment by rluiten** [comment]
I freely admit I might have flubbed something.
But it compiles with no errors and appears to work (but that might be pure fluke).

Definition of my Component and its properties.
```typescript
interface RouteParams {
  transitionStatementId: number;
}
export interface OwnProps extends RouteComponentProps<RouteParams> {}
export const mapDispatchToProps = (dispatch: Dispatch<RootState>) =>
  bindActionCreators(
    {
      getTransitionForm
    },
    dispatch
  );
const stateProps = returntypeof(mapStateToProps);
const dispatchProps = returntypeof(mapDispatchToProps);
export type Props = typeof stateProps & typeof dispatchProps & OwnProps;

class TransitionForm extends React.Component<AllProps, OwnState> { /* etc */ }
```

Inside render() of my component the type of  'props.getTransitionForm` appears to be.
(conveniently visible in VSCode but I did not assume VSCode was correct)

```typescript
(params: GetTransitionFormParams) =>
        (dispatch: Dispatch<RootState>, getState: () => RootState, extraArgument: any) => 
             Promise<any>;
```

The fire*Action() functions are just examples.

I setup a test and i can use `await` it compiles with no errors, and appears to work correctly.

```typescript
    const getPayload = {state, apiUrls, transitionStatementId: 23};
    const getResult  = getTransitionForm(getPayload);
    try {
        await getResult;
        fireGotAction();
    } catch (e) { 
        fireErrorGotAction();
    }
```

If I use .then() I get a compile error.

The `getResult` above gives me the compile error where i try to use .then().
`TS2339: Property 'then' does not exist on type 'ThunkAction<Promise<any>, RootState, any>'.`

```typescript
    const getPayload = {state, apiUrls, transitionStatementId: 23};
    const getResult  = getTransitionForm(getPayload);
    getResult.then(() => fireGotAction(), () => fireErrorGotAction());  
```

This leads me to believe the types are not really correct, I am not implying they are easy to fix or can be fixed, I fudged the type for myself for now. It appears await isn't enforcing type constraints equivalently to `.then()`, and since the underlying value is actually a promise `await` works anyway.

Currently i am just casting the property action to any to call then and all seems well with the world.

Thanks for your response, I raised this more to see if it rings a bell with you that might point out something I had missed or possibly even something you can address. I think its complex enough some sort of fix might not be easy and may require much deeper type knowledge than I have, or even typescript may not be able to do express the constraint in its current version.

Thanks,

**Comment by piotrwitek** [comment]
@rluiten this time I have thoroughly investigated and I found you are right, types are not correct but only for the thunk action creators.
Specifically bindActionCreators and connect could have been augmented by redux-thunk to fix that behaviour. 

The types returned from connect should have bound action creators, but it seems they are still typed as thunk action creators.

When I changed mapDispatchToProps declaration to not use `bindActionCreators` it's fixed, you can try:
const mapDispatchToProps = (dispatch: Dispatch) => ({
  updateRegion: (payload: RegionModel) => dispatch(SitesReducer.updateRegion(payload)),
});

The second one works because this time dispatch is correctly augumented by `redux-thunk` typings.

**Comment by rluiten** [comment]
Awesome, I have learned so much from this, and your answer makes a lot of sense.
Thanks for persisting with this :).

**Comment by piotrwitek** [comment]
@rluiten no problem, me as well learned a new trick :)

I'll add it later to the guide as caveat giving you a well earned credit :)

**Comment by brianpaulcarpenter** [comment]
Hi, I just bumped into this issue as well and indeed switching away from bindActionCreators worked.  Has anyone posted this to the redux team, to see if they can fix it?  I can't find much documentation on this problem other than this thread.  thanks

**Comment by piotrwitek** [comment]
Added a new paragraph warning and explaining root case of this issue: https://github.com/piotrwitek/react-redux-typescript-guide#caveat-with-bindactioncreators

**Comment by njgraf512** [comment]
Possibly helpful to others: I was having this issue as well, but it was resolved once I upgraded `@types/react-redux` to v5.0.19.

**Comment by davidspiess** [comment]
Maybe we should open a issue on https://github.com/DefinitelyTyped/DefinitelyTyped.

**Comment by njgraf512** [comment]
Sorry for the delay responding. It's been a while since I looked at this, but I'll get the conversation started with what I have and see if that's helpful. I'm not totally sure if my code will directly translate, but hopefully, it will be helpful. 

```typescript
type OwnProps = {
  foo: string,
};

type ReduxStateProps = {
  bar: boolean,
};

type DispatchProps = {
  myAC: typeof myAC.bound,
  // note the type of myAC is: (x: CreditDecisionsRequest) => AbortableAction<FluxAction<void>>
  // see below for relevant type definitions of return type
};

type ComponentProps = OwnProps & ReduxStateProps & DispatchProps;

class DecisionDetails extends React.Component<DecisionDetailsProps> { // ... }

function mapStateToProps(state: RootState, props: OwnProps): ReduxStateProps {
  // ...
  return {
    bar: true
  };
}

function mapDispatchToProps(dispatch: Dispatch<RootState>) {
  const acs = {
    myAC,
  };
  return bindActionCreators<typeof acs, DispatchProps>(acs, dispatch);
}

export default connect(mapStateToProps, mapDispatchToProps)(DecisionDetails);
```

For reference, `ReturnType<typeof mapDispatchToProps>` is:

```typescript
{
    myAC: (x: ArgType) => AbortableAction<FluxAction<void>>;
}
```

The utility types involved are:

```typescript
export interface AbortableAction<R> extends BluebirdPromise<R> {
  abort: () => void;
  url: string;
}

export interface FluxAction<Payload> extends Action {
  type: string;
  payload: Payload;
  meta?: any;
  error: boolean;
}

export type ActionCreator<Arg, Payload> = {
  (a: Arg): FluxAction<Payload>,
  type: string,
  bound: (x: Arg) => AbortableAction<FluxAction<Payload>>,
  arg: Arg,
  pl: Payload,
};
```

Hopefully, that helps. Let me know if there are any questions, and I'll try to answer them.

**Comment by RMHonor** [comment]
If people are still looking at how to get the correct typings for `bindActionCreators` when passing in ThunkActions, I've got an open PR to fix this, specifically the line: https://github.com/reduxjs/redux-thunk/pull/224/files#diff-b52768974e6bc0faccb7d4b75b162c99R31

Overloading the function definition and conditionally returning a different object type if the action passed is of type `ThunkAction`:

```typescript
declare module 'redux' {
  /**
   * Overload for bindActionCreators redux function, returns expects responses
   * from thunk actions
   */
  function bindActionCreators<M extends ActionCreatorsMapObject<any>>(
    actionCreators: M,
    dispatch: Dispatch,
  ): { [N in keyof M]: ReturnType<M[N]> extends ThunkAction<any, any, any, any> ? (...args: Parameters<M[N]>) => ReturnType<ReturnType<M[N]>> : M[N] }
}
```

Let me know if it fits your needs

**Comment by ablakey** [comment]
Thanks for this. Using this branch in my code and it address the above issue. Here's an example of how I'm using it for others who come across this (because I always appreciate having lots of tangible examples).

```typescript
import React from 'react';
import { bindActionCreators, AnyAction } from 'redux';
import { ThunkDispatch } from 'redux-thunk';
import {AppState} from './AppState'

// Types to cut down on boilerplate across dozens of thunks.
type Dispatcher = ThunkDispatch<AppState, undefined, AnyAction>;
type GetState = () => AppState;

const getAuthToken = (username: string, password: string) => {
  return async (dispatch: Dispatcher, getState: GetState) => {
    await request.post(`auth/url/`).send({ username, password });
    return dispatch({ type: 'SET_AUTH_TOKEN', token: res.body.token, username });
  };
};

// Before this PR, `bindActionCreators` would mess up the typing, causing an error below...
const mapDispatch = (dispatch: Dispatcher) => bindActionCreators({
  getAuthToken,
}, dispatch);

type Props = ReturnType<typeof mapDispatch>;

class MyComponent extends React.PureComponent<Props> {

  public render() {
    // Before this PR, the line below would complain that we can't await non-Promises.
    // the bindActionCreators was messing up the typing so it thought we were returning a
    // normal function, not an async function.
    await this.props.getAuthToken('username', 'password');
    console.log('Then I do something else.');
  }
}


export default connect(null, mapDispatch)(MyComponent)


```

**Comment by chrispaynter** [comment]
> The necessary fix is to augment bindActionCreators to apply augmented dispatch that can handle thunk actions, but it's not possible with current Type Inference limitations.

Thought I was going crazy till I found this thread :)

Does this still hold true @piotrwitek?

**Comment by piotrwitek** [comment]
Not sure, I haven't used thunks for quite a while. But type definitions correction for bindActionCreators was merged few days ago, so might be fixed soon https://github.com/reduxjs/redux-thunk/pull/224
