### ISSUE TITLE
Better Typing for Component Callback Props

### ISSUE THREAD

**Issue by vinnichase** [piotrwitek/react-redux-typescript-guide#70]
Hey there,

great guide! You recommend [here](https://github.com/piotrwitek/react-redux-typescript-guide#caveat-with-bindactioncreators) to type the callbacks as `() => any` that did the trick for me and lead me to a better typed alternative since you know the actual type of the action creators: 
`typeof actionCreator`.

```typescript
import * as React from 'react';
import { connect } from 'react-redux';
import { RootState } from '@src/redux';
import { actionCreator } from '@src/redux/actions';

interface ReduxProps {
    action: typeof actionCreator; // <- instead of: action: () => any;
}

interface Props {
    label: string;
}

interface State {
    value: string;
}

class YourComp extends React.Component<Props & ReduxProps, State> {
    public componentWillMount() {
        this.props.action();
    }

    public render() {
        // render
    }
}

function mapStateToProps(state: RootState, props: Props): Props {
    return { ...props };
}

export default connect(mapStateToProps, { action: actionCreator })(YourComp); // <- Compiler will not complain
```
This at least works in TypeScript 2.8 so I hope that can help to refine your guide!

Best
Vinni

**Comment by piotrwitek** [comment]
Hi, sorry but this is only the case for half of the problem, the problem still holds for not connected components where you don't want to tightly couple to the action creator to allow reusablility.
