### ISSUE TITLE
ReadonlyRecursive / DeepReadonly is now available

### ISSUE THREAD

**Issue by jeremejevs** [piotrwitek/react-redux-typescript-guide#71]
https://github.com/Microsoft/TypeScript/issues/10725#issuecomment-381409874

**Comment by piotrwitek** [comment]
Yes it is for quite some time https://github.com/piotrwitek/utility-types#deepreadonlyt
I'm preparing a big update to the guide soon that will include it

**Comment by jeremejevs** [comment]
:+1:
