### ISSUE TITLE
Tried to build and got errors

### ISSUE THREAD

**Issue by biolau** [piotrwitek/react-redux-typescript-guide#8]
$ npm run build

> react-redux-typescript-guide@1.0.0 prebuild c:\projects\react-redux-typescript-guide\examples
> rm -rf out

> react-redux-typescript-guide@1.0.0 build c:\projects\react-redux-typescript-guide\examples
> tsc -p ./

1 import * as uuid from 'uuid';
              ~~~~

src/api/articles.ts(1,13): error TS6133: 'uuid' is declared but never used.


8 const articlesResponse = require('./fixtures/articles.json');
        ~~~~~~~~~~~~~~~~

src/api/articles.ts(8,7): error TS6133: 'articlesResponse' is declared but never used.

7 import { actionCreators } from '../modules/converter';
                                 ~~~~~~~~~~~~~~~~~~~~~~

src/components/connected-stateless-counter.tsx(7,32): error TS2307: Cannot find module '../modules/converter'.


14   counter: state.converter.counter,
                              ~~~~~~~

src/components/connected-stateless-counter.tsx(14,28): error TS2339: Property 'counter' does not exist on type 'IState'.


24 const checkProps: IStatelessCounterProps = { ...stateProps, ...dispatchProps };
         ~~~~~~~~~~

src/components/connected-stateless-counter.tsx(24,7): error TS6133: 'checkProps' is declared but never used.


8     <ConnectedStatelessCounter label="ConnectedStatelessCounter" />
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/containers/home.tsx(8,32): error TS2322: Type '{ label: "ConnectedStatelessCounter"; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<IStatelessCounterProps, ComponentState>>...'.
  Type '{ label: "ConnectedStatelessCounter"; }' is not assignable to type 'Readonly<IStatelessCounterProps>'.
    Property 'counter' is missing in type '{ label: "ConnectedStatelessCounter"; }'.

**Comment by piotrwitek** [comment]
Hello
This is not a boilerplate or a working project, it's just my playground to test patterns

**Comment by biolau** [comment]
No problem. I am struggling with this technology mix and not finding good examples so a boilerplate would have helped a lot.

I really appreciate your guide! Thank you for the good work!

**Comment by piotrwitek** [comment]
Thanks :)
You can check this one as a starting point, but probably need to spend some time on webpack config but it's hard to find something that answer all the needs: https://github.com/piotrwitek/react-redux-typescript-webpack-starter
