### ISSUE TITLE
Provide Example For `with-error-boundary` onReset

### ISSUE THREAD

**Issue by sylvanaar** [piotrwitek/react-redux-typescript-guide#83]
I get what `onReset` does, but what is the motivation behind it? If a component fails, why should we reset the error, and when? It would be helpful to show it in use - just to understand why it is there from the author's perspective.

**Comment by piotrwitek** [comment]
It was a bit contrived example, you would want to redirect/reset invalid state as well when invoking `onReset`

**Comment by sylvanaar** [comment]
Ok, I thought you were recommending it as part of the pattern - and was curious about its purpose, but I get it now. Thank You!
