### ISSUE TITLE
React.ReactElement is missing parts of text

### ISSUE THREAD

**Issue by lazarljubenovic** [piotrwitek/react-redux-typescript-guide#88]
![image](https://user-images.githubusercontent.com/7661457/43303512-5cb776f2-9170-11e8-9d30-a3e3ae957ec0.png)

Not sure what's supposed to be here, but not this, right? The parenthesis are missing the content.

**Comment by piotrwitek** [comment]
This is pseudo-code demonstrating what this type will accept, to not repeat it multiline I decided to put it in short-circuit format, do you have a better approach?

**Comment by lazarljubenovic** [comment]
Are we talking about the same thing? I meant the parenthesis in text, after "DOM component" and "composite component". There's a pair of "()" which have no content inside. I assume there's something missing inside?

**Comment by piotrwitek** [comment]
Ah... sorry I have misinterpreted :)
Yeah this seems like something is wrong there, thanks for the info.

**Comment by henrikra** [comment]
@piotrwitek Yeah looks like there are two pieces of empty braces `()` for some reason? 🤔
